theme: jekyll-theme-midnight
title: Fulbright Specialist to Morocco
description: Site to house instructions, code, and data for Fulbright Specialist trip to Morocco in 2022.

#Layout
show_social: true

# Menu
navigation: 
  -{file: "index.html", title: "Home", icon: home}
  #-{file: "open-refine.md", title: "Open Refine", icon: address-card}
  
# External

external: 
  -{title: Mail, icon: enevelope, url: "mailto:hannah8@purdue.edu"}
  -{title: Github, icon: github, url: "https://github.com/m-n-hannah"}
  -{title: Twitter, icon: twitter, url: "https://twitter.com/TinkeringHuman"}
